name: build-and-deploy

on:
  pull_request:
    types: 
      - closed
    branches: 
      - main
      - Development

env:
  TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}

jobs:
  # To build the project
  build-project:
    runs-on: ubuntu-latest
     
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Set environment variables
        run: |
          echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.DEVELOPMENT_API_URL }}" >> $GITHUB_ENV
          echo "ANOTHER_SECRET=${{ secrets.ANOTHER_SECRET }}" >> $GITHUB_ENV
          grep -q "^NEXT_PUBLIC_API_BASE_URL=" .env && sed -i "s/^NEXT_PUBLIC_API_BASE_URL=.*/NEXT_PUBLIC_API_BASE_URL=${{ secrets.DEVELOPMENT_API_URL }}/" .env || echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.DEVELOPMENT_API_URL }}" >> .env

      - name: Installing dependencies
        run: npm install --legacy-peer-deps

      - name: Building project
        run: npm run build
      
      - name: Deploy to EC2
        if: github.event.pull_request.base.ref == 'Development'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /plane-ui/plane-web-staging/plane_web
            nvm use 21
            npm install --legacy-peer-deps
            npm run build
            sudo service nginx restart
            pm2 restart plane-frontend
